name: Landor7
favicon: null
layout_spectrum: 0.8860212853178382
typography_spectrum: 0.8885114437434822
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9713783909101039
  lightness: 0.12688873964361846
  saturation: 0.8565105779562145
  rhythmicContrast: 0.8443544406909496
purpose: []
