name: Landor7
favicon: null
layout_spectrum: 0
typography_spectrum: 0.02104
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#253f46'
    - '#344e55'
    - '#0d1d25'
    - '#3c5a5f'
    - '#01101b'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
