name: Landor7
favicon: null
layout_spectrum: 0.90303
typography_spectrum: 0.02104
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#600508'
    - '#ab0914'
    - '#252525'
    - '#ef1139'
  brandStrength: 0.9713783909101039
  lightness: 0.12688873964361846
  saturation: 0.8565105779562145
  rhythmicContrast: 0.8443544406909496
purpose: []
